import type { Claim, ClaimDocument, ClaimMessage } from "@/lib/types"

export const MOCK_USER_ID = "mock-importer-001"
export const MOCK_SUPPLIER_ID = "mock-supplier-001"

export const MOCK_CLAIMS: Claim[] = [
  {
    claim_id: "clm-001",
    container_number: "DOLE2234567",
    invoice_number: "INV-2024-0081",
    supplier_name: "Dole Food Company",
    status: "In Review",
    stuffing_date: "2024-11-12",
    release_date: "2024-12-03",
    waste_percentage: 18.5,
    claim_summary:
      "Container arrived with significant moisture damage affecting the top two pallet layers. Surveyor inspection conducted on Dec 5. Supplier has uploaded pre-stuffing QC report showing normal conditions at origin. Importer awaiting final surveyor invoice before proceeding to negotiation.",
    damage_type: "Moisture",
    affected_units: 240,
    total_units: 1300,
    estimated_loss_usd: 14200,
    damage_description:
      "Top two layers of pallets showed heavy moisture damage consistent with condensation during transit. Product discoloration and mold detected on approximately 240 cartons. Temperature logger data shows deviation above 8°C during the last 48 hours of voyage.",
    damage_location: "Top 2 pallet layers",
    temperature_log_present: true,
    inspector_name: "Carlos Mendez",
    inspection_date: "2024-12-05",
    supplier_user_id: MOCK_SUPPLIER_ID,
    created_by: MOCK_USER_ID,
    created_at: "2024-12-04T09:15:00Z",
    updated_at: "2024-12-06T14:30:00Z",
  },
  {
    claim_id: "clm-002",
    container_number: "CHIQ9981122",
    invoice_number: "INV-2024-0095",
    supplier_name: "Chiquita Brands",
    status: "Open",
    stuffing_date: "2024-11-28",
    release_date: "2024-12-18",
    waste_percentage: 9.2,
    claim_summary: null,
    damage_type: "Physical",
    affected_units: 80,
    total_units: 870,
    estimated_loss_usd: 5600,
    damage_description:
      "Multiple cartons arrived crushed, likely due to improper stacking. External boxes intact but internal fruit bruised beyond sale grade.",
    damage_location: "Middle section, rows 4–6",
    temperature_log_present: false,
    inspector_name: "Sarah Kim",
    inspection_date: "2024-12-19",
    supplier_user_id: MOCK_SUPPLIER_ID,
    created_by: MOCK_USER_ID,
    created_at: "2024-12-19T11:00:00Z",
    updated_at: "2024-12-19T11:00:00Z",
  },
  {
    claim_id: "clm-003",
    container_number: "FYFF4456789",
    invoice_number: "INV-2024-0072",
    supplier_name: "Fyffes International",
    status: "Resolved",
    stuffing_date: "2024-10-05",
    release_date: "2024-10-29",
    waste_percentage: 6.1,
    claim_summary:
      "Claim resolved on Nov 14. Supplier agreed to credit USD 3,200 against next invoice. Both parties signed settlement agreement. Surveyor report accepted as final evidence.",
    damage_type: "Contamination",
    affected_units: 55,
    total_units: 900,
    estimated_loss_usd: 3200,
    damage_description:
      "Slight off-odour detected in 55 cartons, possibly from adjacent cargo contamination during loading.",
    damage_location: "Rear wall, bottom row",
    temperature_log_present: true,
    inspector_name: "David Osei",
    inspection_date: "2024-10-31",
    supplier_user_id: MOCK_SUPPLIER_ID,
    created_by: MOCK_USER_ID,
    created_at: "2024-10-31T08:00:00Z",
    updated_at: "2024-11-14T16:45:00Z",
  },
  {
    claim_id: "clm-004",
    container_number: "DOLE3398001",
    invoice_number: "INV-2025-0004",
    supplier_name: "Dole Food Company",
    status: "Open",
    stuffing_date: "2025-01-10",
    release_date: "2025-01-31",
    waste_percentage: 22.0,
    claim_summary: null,
    damage_type: "Temperature",
    affected_units: 310,
    total_units: 1410,
    estimated_loss_usd: 21000,
    damage_description:
      "Reefer unit malfunction suspected. Product arrived partially ripened and unfit for retail. Temperature logger shows extended period above 14°C.",
    damage_location: "Full container — uniform ripening",
    temperature_log_present: true,
    inspector_name: null,
    inspection_date: null,
    supplier_user_id: MOCK_SUPPLIER_ID,
    created_by: MOCK_USER_ID,
    created_at: "2025-01-31T13:20:00Z",
    updated_at: "2025-01-31T13:20:00Z",
  },
]

export const MOCK_DOCUMENTS: ClaimDocument[] = [
  {
    doc_id: "doc-001",
    claim_id: "clm-001",
    zone: "pre_stuffing_qc",
    file_name: "QC_Report_DOLE2234567_Nov12.pdf",
    file_path: "clm-001/pre_stuffing_qc/QC_Report_DOLE2234567_Nov12.pdf",
    file_size: 248000,
    mime_type: "application/pdf",
    uploaded_by: MOCK_SUPPLIER_ID,
    uploaded_at: "2024-11-13T07:40:00Z",
  },
  {
    doc_id: "doc-002",
    claim_id: "clm-001",
    zone: "supporting_documents",
    file_name: "Surveyor_Damage_Report_Dec05.pdf",
    file_path: "clm-001/supporting_documents/Surveyor_Damage_Report_Dec05.pdf",
    file_size: 1020000,
    mime_type: "application/pdf",
    uploaded_by: MOCK_USER_ID,
    uploaded_at: "2024-12-05T15:10:00Z",
  },
  {
    doc_id: "doc-003",
    claim_id: "clm-001",
    zone: "supporting_documents",
    file_name: "Container_Photos_Dec03.jpg",
    file_path: "clm-001/supporting_documents/Container_Photos_Dec03.jpg",
    file_size: 3400000,
    mime_type: "image/jpeg",
    uploaded_by: MOCK_USER_ID,
    uploaded_at: "2024-12-03T18:55:00Z",
  },
  {
    doc_id: "doc-004",
    claim_id: "clm-001",
    zone: "additional_costs_invoices",
    file_name: "Surveyor_Invoice_INV-SRV-441.pdf",
    file_path: "clm-001/additional_costs_invoices/Surveyor_Invoice_INV-SRV-441.pdf",
    file_size: 180000,
    mime_type: "application/pdf",
    uploaded_by: MOCK_USER_ID,
    uploaded_at: "2024-12-06T09:00:00Z",
  },
]

export const MOCK_MESSAGES: ClaimMessage[] = [
  {
    message_id: "msg-001",
    claim_id: "clm-001",
    sender_id: MOCK_USER_ID,
    sender_role: "importer",
    body: "Hello — we received container DOLE2234567 on Dec 3 and found significant moisture damage on the top two pallet layers. I've attached the surveyor report and photos. Please review and confirm receipt.",
    created_at: "2024-12-05T10:00:00Z",
  },
  {
    message_id: "msg-002",
    claim_id: "clm-001",
    sender_id: MOCK_SUPPLIER_ID,
    sender_role: "supplier",
    body: "Thank you for notifying us. We've reviewed the initial photos. Our QC report at origin (uploaded above) showed no anomalies at stuffing. We believe the damage may have occurred during transit. We'll review the surveyor findings and come back to you by end of week.",
    created_at: "2024-12-05T14:30:00Z",
  },
  {
    message_id: "msg-003",
    claim_id: "clm-001",
    sender_id: MOCK_USER_ID,
    sender_role: "importer",
    body: "Understood. We've also uploaded the surveyor's invoice (doc-004). The total additional cost incurred is USD 1,800 for the survey. Please factor this into the settlement discussion.",
    created_at: "2024-12-06T09:15:00Z",
  },
  {
    message_id: "msg-004",
    claim_id: "clm-001",
    sender_id: MOCK_SUPPLIER_ID,
    sender_role: "supplier",
    body: "Acknowledged. We are escalating internally. We will respond with a formal position on liability by Dec 10.",
    created_at: "2024-12-06T16:00:00Z",
  },
]
